backend:
  name: test-repo

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "berita"
    label: "Berita"
    folder: "content/berita"
    create: true

    fields:
      - label: "Judul"
        name: "title"
        widget: "string"

      - label: "Tanggal"
        name: "date"
        widget: "datetime"

      - label: "Isi"
        name: "body"
        widget: "markdown"